---
name: "helm-action"
description: "Does Helm stuff"
inputs:
  # Inputs from kubectl-action-base
  debug:
    description: "Adds action debug messages. Might contain sensitive data."
    required: false
  config:
    description: "Kubeconfig yaml contents. Can be base64 encoded or just yaml."
    required: false
  eks_cluster:
    description: "Name of the EKS cluster to interact with. Will use aws eks update-kubeconfig."
    required: false
  eks_role_arn:
    description: "The AWS IAM role to use when authenticating with EKS."
    required: false
  context:
    description: "Context to use if there are multiple."
    required: false
  # helm-action specific inputs
  namespace:
    description: "Namespace to deploy to. You can use env vars here."
    required: true
  create_namespace:
    description: "Should we create the specified namespace."
    required: false
    default: "true"
  release:
    description: "Helm release name. You can use env vars here."
    required: true
  chart:
    description: "Helm chart path."
    required: false
    default: "./"
  app_version:
    description: "The version to set AppVersion in Chart.yaml"
    required: false
  values:
    description: "Helm values to be used in addition to the values file."
    required: false
  values_files:
    description: "Helm values files paths, comma separated. Will be used in order provided."
    required: false
  atomic:
    description: "Adds --atomic flag to helm."
    required: false
  wait:
    description: "Adds --wait flag to helm."
    required: false
  timeout:
    description: "Adds --timeout flag to helm."
    required: false
  github_summary:
    description: "Should we write helm status to github step summary."
    required: false
    default: "true"
  github_summary_strip_commands:
    description: "Should we remove any ::github::commands from the summary."
    required: false
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
